# =============================================================================
# GENERATED FILE — do not edit by hand. Source of truth: fleet_manager.proto
# =============================================================================
# gRPC stubs/servicers for the FleetManager control-plane service (agents,
# plans, tasks, goals, allocate/start). Regenerate with protoc / grpc_tools
# when the .proto changes. Exhaustive field/RPC docs live in the .proto.
# =============================================================================
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fleet_manager_pb2 as fleet__manager__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fleet_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetManagerStub(object):
    """Service definition for agent fleet management
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterAgent = channel.unary_unary(
                '/agent_fleet.FleetManager/RegisterAgent',
                request_serializer=fleet__manager__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)
        self.UnregisterAgent = channel.unary_unary(
                '/agent_fleet.FleetManager/UnregisterAgent',
                request_serializer=fleet__manager__pb2.UnregisterAgentRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.UnregisterAgentResponse.FromString,
                _registered_method=True)
        self.DeployAgent = channel.unary_unary(
                '/agent_fleet.FleetManager/DeployAgent',
                request_serializer=fleet__manager__pb2.DeployAgentRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.DeployAgentResponse.FromString,
                _registered_method=True)
        self.UndeployAgent = channel.unary_unary(
                '/agent_fleet.FleetManager/UndeployAgent',
                request_serializer=fleet__manager__pb2.UndeployAgentRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.UndeployAgentResponse.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/agent_fleet.FleetManager/ListAgents',
                request_serializer=fleet__manager__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.GetAgent = channel.unary_unary(
                '/agent_fleet.FleetManager/GetAgent',
                request_serializer=fleet__manager__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.GetAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentStatus = channel.unary_unary(
                '/agent_fleet.FleetManager/GetAgentStatus',
                request_serializer=fleet__manager__pb2.GetAgentStatusRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.AgentStatus.FromString,
                _registered_method=True)
        self.CreatePlan = channel.unary_unary(
                '/agent_fleet.FleetManager/CreatePlan',
                request_serializer=fleet__manager__pb2.CreatePlanRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.CreatePlanResponse.FromString,
                _registered_method=True)
        self.GetPlan = channel.unary_unary(
                '/agent_fleet.FleetManager/GetPlan',
                request_serializer=fleet__manager__pb2.GetPlanRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.GetPlanResponse.FromString,
                _registered_method=True)
        self.ListPlans = channel.unary_unary(
                '/agent_fleet.FleetManager/ListPlans',
                request_serializer=fleet__manager__pb2.ListPlansRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.ListPlansResponse.FromString,
                _registered_method=True)
        self.DeletePlan = channel.unary_unary(
                '/agent_fleet.FleetManager/DeletePlan',
                request_serializer=fleet__manager__pb2.DeletePlanRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.DeletePlanResponse.FromString,
                _registered_method=True)
        self.CreateTask = channel.unary_unary(
                '/agent_fleet.FleetManager/CreateTask',
                request_serializer=fleet__manager__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.CreateTaskResponse.FromString,
                _registered_method=True)
        self.UpdateTask = channel.unary_unary(
                '/agent_fleet.FleetManager/UpdateTask',
                request_serializer=fleet__manager__pb2.UpdateTaskRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.UpdateTaskResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/agent_fleet.FleetManager/GetTask',
                request_serializer=fleet__manager__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.GetTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/agent_fleet.FleetManager/ListTasks',
                request_serializer=fleet__manager__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.DeleteTask = channel.unary_unary(
                '/agent_fleet.FleetManager/DeleteTask',
                request_serializer=fleet__manager__pb2.DeleteTaskRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.DeleteTaskResponse.FromString,
                _registered_method=True)
        self.CreateGoal = channel.unary_unary(
                '/agent_fleet.FleetManager/CreateGoal',
                request_serializer=fleet__manager__pb2.CreateGoalRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.CreateGoalResponse.FromString,
                _registered_method=True)
        self.GetGoal = channel.unary_unary(
                '/agent_fleet.FleetManager/GetGoal',
                request_serializer=fleet__manager__pb2.GetGoalRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.GetGoalResponse.FromString,
                _registered_method=True)
        self.ListGoals = channel.unary_unary(
                '/agent_fleet.FleetManager/ListGoals',
                request_serializer=fleet__manager__pb2.ListGoalsRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.ListGoalsResponse.FromString,
                _registered_method=True)
        self.DeleteGoal = channel.unary_unary(
                '/agent_fleet.FleetManager/DeleteGoal',
                request_serializer=fleet__manager__pb2.DeleteGoalRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.DeleteGoalResponse.FromString,
                _registered_method=True)
        self.StartPlan = channel.unary_unary(
                '/agent_fleet.FleetManager/StartPlan',
                request_serializer=fleet__manager__pb2.StartPlanRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.StartPlanResponse.FromString,
                _registered_method=True)
        self.AllocatePlan = channel.unary_unary(
                '/agent_fleet.FleetManager/AllocatePlan',
                request_serializer=fleet__manager__pb2.AllocatePlanRequest.SerializeToString,
                response_deserializer=fleet__manager__pb2.AllocatePlanResponse.FromString,
                _registered_method=True)


class FleetManagerServicer(object):
    """Service definition for agent fleet management
    """

    def RegisterAgent(self, request, context):
        """Register agent metadata with the central node (stores in etcd)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterAgent(self, request, context):
        """Unregister a agent from the central node
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployAgent(self, request, context):
        """Deploy a container for a registered agent using stored configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UndeployAgent(self, request, context):
        """Undeploy (stop and remove) a agent container
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """List all agents
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Get a specific agent by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """Get detailed status of a specific agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePlan(self, request, context):
        """Planning
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlans(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTask(self, request, context):
        """Task management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateGoal(self, request, context):
        """Goal management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListGoals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocatePlan(self, request, context):
        """Allocate agents to an existing (unallocated) plan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=fleet__manager__pb2.RegisterAgentRequest.FromString,
                    response_serializer=fleet__manager__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'UnregisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterAgent,
                    request_deserializer=fleet__manager__pb2.UnregisterAgentRequest.FromString,
                    response_serializer=fleet__manager__pb2.UnregisterAgentResponse.SerializeToString,
            ),
            'DeployAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployAgent,
                    request_deserializer=fleet__manager__pb2.DeployAgentRequest.FromString,
                    response_serializer=fleet__manager__pb2.DeployAgentResponse.SerializeToString,
            ),
            'UndeployAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.UndeployAgent,
                    request_deserializer=fleet__manager__pb2.UndeployAgentRequest.FromString,
                    response_serializer=fleet__manager__pb2.UndeployAgentResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=fleet__manager__pb2.ListAgentsRequest.FromString,
                    response_serializer=fleet__manager__pb2.ListAgentsResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=fleet__manager__pb2.GetAgentRequest.FromString,
                    response_serializer=fleet__manager__pb2.GetAgentResponse.SerializeToString,
            ),
            'GetAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentStatus,
                    request_deserializer=fleet__manager__pb2.GetAgentStatusRequest.FromString,
                    response_serializer=fleet__manager__pb2.AgentStatus.SerializeToString,
            ),
            'CreatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePlan,
                    request_deserializer=fleet__manager__pb2.CreatePlanRequest.FromString,
                    response_serializer=fleet__manager__pb2.CreatePlanResponse.SerializeToString,
            ),
            'GetPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPlan,
                    request_deserializer=fleet__manager__pb2.GetPlanRequest.FromString,
                    response_serializer=fleet__manager__pb2.GetPlanResponse.SerializeToString,
            ),
            'ListPlans': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlans,
                    request_deserializer=fleet__manager__pb2.ListPlansRequest.FromString,
                    response_serializer=fleet__manager__pb2.ListPlansResponse.SerializeToString,
            ),
            'DeletePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePlan,
                    request_deserializer=fleet__manager__pb2.DeletePlanRequest.FromString,
                    response_serializer=fleet__manager__pb2.DeletePlanResponse.SerializeToString,
            ),
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=fleet__manager__pb2.CreateTaskRequest.FromString,
                    response_serializer=fleet__manager__pb2.CreateTaskResponse.SerializeToString,
            ),
            'UpdateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTask,
                    request_deserializer=fleet__manager__pb2.UpdateTaskRequest.FromString,
                    response_serializer=fleet__manager__pb2.UpdateTaskResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=fleet__manager__pb2.GetTaskRequest.FromString,
                    response_serializer=fleet__manager__pb2.GetTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=fleet__manager__pb2.ListTasksRequest.FromString,
                    response_serializer=fleet__manager__pb2.ListTasksResponse.SerializeToString,
            ),
            'DeleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTask,
                    request_deserializer=fleet__manager__pb2.DeleteTaskRequest.FromString,
                    response_serializer=fleet__manager__pb2.DeleteTaskResponse.SerializeToString,
            ),
            'CreateGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGoal,
                    request_deserializer=fleet__manager__pb2.CreateGoalRequest.FromString,
                    response_serializer=fleet__manager__pb2.CreateGoalResponse.SerializeToString,
            ),
            'GetGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoal,
                    request_deserializer=fleet__manager__pb2.GetGoalRequest.FromString,
                    response_serializer=fleet__manager__pb2.GetGoalResponse.SerializeToString,
            ),
            'ListGoals': grpc.unary_unary_rpc_method_handler(
                    servicer.ListGoals,
                    request_deserializer=fleet__manager__pb2.ListGoalsRequest.FromString,
                    response_serializer=fleet__manager__pb2.ListGoalsResponse.SerializeToString,
            ),
            'DeleteGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGoal,
                    request_deserializer=fleet__manager__pb2.DeleteGoalRequest.FromString,
                    response_serializer=fleet__manager__pb2.DeleteGoalResponse.SerializeToString,
            ),
            'StartPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPlan,
                    request_deserializer=fleet__manager__pb2.StartPlanRequest.FromString,
                    response_serializer=fleet__manager__pb2.StartPlanResponse.SerializeToString,
            ),
            'AllocatePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocatePlan,
                    request_deserializer=fleet__manager__pb2.AllocatePlanRequest.FromString,
                    response_serializer=fleet__manager__pb2.AllocatePlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent_fleet.FleetManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent_fleet.FleetManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetManager(object):
    """Service definition for agent fleet management
    """

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/RegisterAgent',
            fleet__manager__pb2.RegisterAgentRequest.SerializeToString,
            fleet__manager__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/UnregisterAgent',
            fleet__manager__pb2.UnregisterAgentRequest.SerializeToString,
            fleet__manager__pb2.UnregisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/DeployAgent',
            fleet__manager__pb2.DeployAgentRequest.SerializeToString,
            fleet__manager__pb2.DeployAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UndeployAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/UndeployAgent',
            fleet__manager__pb2.UndeployAgentRequest.SerializeToString,
            fleet__manager__pb2.UndeployAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/ListAgents',
            fleet__manager__pb2.ListAgentsRequest.SerializeToString,
            fleet__manager__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/GetAgent',
            fleet__manager__pb2.GetAgentRequest.SerializeToString,
            fleet__manager__pb2.GetAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/GetAgentStatus',
            fleet__manager__pb2.GetAgentStatusRequest.SerializeToString,
            fleet__manager__pb2.AgentStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/CreatePlan',
            fleet__manager__pb2.CreatePlanRequest.SerializeToString,
            fleet__manager__pb2.CreatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/GetPlan',
            fleet__manager__pb2.GetPlanRequest.SerializeToString,
            fleet__manager__pb2.GetPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/ListPlans',
            fleet__manager__pb2.ListPlansRequest.SerializeToString,
            fleet__manager__pb2.ListPlansResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/DeletePlan',
            fleet__manager__pb2.DeletePlanRequest.SerializeToString,
            fleet__manager__pb2.DeletePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/CreateTask',
            fleet__manager__pb2.CreateTaskRequest.SerializeToString,
            fleet__manager__pb2.CreateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/UpdateTask',
            fleet__manager__pb2.UpdateTaskRequest.SerializeToString,
            fleet__manager__pb2.UpdateTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/GetTask',
            fleet__manager__pb2.GetTaskRequest.SerializeToString,
            fleet__manager__pb2.GetTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/ListTasks',
            fleet__manager__pb2.ListTasksRequest.SerializeToString,
            fleet__manager__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/DeleteTask',
            fleet__manager__pb2.DeleteTaskRequest.SerializeToString,
            fleet__manager__pb2.DeleteTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/CreateGoal',
            fleet__manager__pb2.CreateGoalRequest.SerializeToString,
            fleet__manager__pb2.CreateGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/GetGoal',
            fleet__manager__pb2.GetGoalRequest.SerializeToString,
            fleet__manager__pb2.GetGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListGoals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/ListGoals',
            fleet__manager__pb2.ListGoalsRequest.SerializeToString,
            fleet__manager__pb2.ListGoalsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/DeleteGoal',
            fleet__manager__pb2.DeleteGoalRequest.SerializeToString,
            fleet__manager__pb2.DeleteGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/StartPlan',
            fleet__manager__pb2.StartPlanRequest.SerializeToString,
            fleet__manager__pb2.StartPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocatePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent_fleet.FleetManager/AllocatePlan',
            fleet__manager__pb2.AllocatePlanRequest.SerializeToString,
            fleet__manager__pb2.AllocatePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
