# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import telemetry_pb2 as telemetry__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in telemetry_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryIngestionStub(object):
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_stream(
                '/robot_fleet.telemetry.TelemetryIngestion/StreamTelemetry',
                request_serializer=telemetry__pb2.TelemetryEvent.SerializeToString,
                response_deserializer=telemetry__pb2.IngestAck.FromString,
                _registered_method=True)
        self.IngestBatch = channel.unary_unary(
                '/robot_fleet.telemetry.TelemetryIngestion/IngestBatch',
                request_serializer=telemetry__pb2.TelemetryBatch.SerializeToString,
                response_deserializer=telemetry__pb2.IngestAck.FromString,
                _registered_method=True)


class TelemetryIngestionServicer(object):
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    def StreamTelemetry(self, request_iterator, context):
        """Bidirectional streaming: robot sends events, server sends acks.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestBatch(self, request, context):
        """Unary batch ingest (HTTP-friendly via gRPC-gateway or transcoding).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryIngestionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=telemetry__pb2.TelemetryEvent.FromString,
                    response_serializer=telemetry__pb2.IngestAck.SerializeToString,
            ),
            'IngestBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestBatch,
                    request_deserializer=telemetry__pb2.TelemetryBatch.FromString,
                    response_serializer=telemetry__pb2.IngestAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_fleet.telemetry.TelemetryIngestion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_fleet.telemetry.TelemetryIngestion', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TelemetryIngestion(object):
    """---------------------------------------------------------------------------
    gRPC service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robot_fleet.telemetry.TelemetryIngestion/StreamTelemetry',
            telemetry__pb2.TelemetryEvent.SerializeToString,
            telemetry__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_fleet.telemetry.TelemetryIngestion/IngestBatch',
            telemetry__pb2.TelemetryBatch.SerializeToString,
            telemetry__pb2.IngestAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
