"""Select agent directories from a fleet file and render their Compose services."""

from __future__ import annotations

from dataclasses import dataclass

from packages.platform_config import load_platform, published_host_ports


class FleetSelectionError(ValueError):
    """A fleet document is malformed or selects an impossible set of agents."""


@dataclass(frozen=True)
class RegisteredAgent:
    """One loadable agent directory known to a domain registry."""

    agent_id: str
    directory: str
    port: int


@dataclass(frozen=True)
class SelectedAgent:
    """One agent chosen by a fleet file, with container and host port mapping."""

    agent_id: str
    path: str
    port: int
    host_port: int

    @property
    def working_dir(self) -> str:
        """Container working directory for this agent's sources."""
        prefix = str(load_platform()["agent_compose"]["working_dir_prefix"]).rstrip("/")
        return f"{prefix}/{self.path}"


def select_agents(document: object, agents: list[RegisteredAgent]) -> list[SelectedAgent]:
    """Return the agents a fleet document includes, ordered by port.

    The document has one key, ``agents``. Each entry is a directory path
    relative to the repository, relative to ``agents/``, or that directory's
    ``config.yaml``.
    """
    if not isinstance(document, dict):
        raise FleetSelectionError("Fleet file must be a mapping")
    if set(document) != {"agents"}:
        unknown = sorted(set(document) - {"agents"})
        if unknown:
            raise FleetSelectionError(
                f"Unknown fleet field {unknown[0]}. The only field is agents."
            )
        raise FleetSelectionError("Fleet file needs an agents list of directory paths")

    by_path = {agent.directory: agent for agent in agents}
    chosen: dict[str, RegisteredAgent] = {}
    for raw in _as_list(document.get("agents"), "agents"):
        agent = _agent_for_path(raw, by_path)
        chosen[agent.agent_id] = agent

    selected = [
        SelectedAgent(agent.agent_id, agent.directory, agent.port, _host_port(agent.port))
        for agent in chosen.values()
    ]
    selected.sort(key=lambda item: (item.port, item.agent_id))
    published = [item.host_port for item in selected]
    if len(published) != len(set(published)):
        raise FleetSelectionError("Selected agents publish the same host port")
    return selected


def render_compose(agents: list[SelectedAgent], environment: dict[str, str]) -> str:
    """Render a Docker Compose document for the selected agents."""
    import yaml

    platform = load_platform()["agent_compose"]
    services = {
        agent.agent_id: {
            "image": platform["image"],
            "build": {
                "context": platform["build_context"],
                "dockerfile": platform["dockerfile"],
            },
            "working_dir": agent.working_dir,
            "command": list(platform["command"]),
            "ports": [f"{agent.host_port}:{agent.port}"],
            "restart": platform["restart"],
            "environment": dict(environment),
            "networks": [platform["network"]],
        }
        for agent in agents
    }
    document = {
        "name": platform["project"],
        "services": services,
        "networks": {
            platform["network"]: {
                "external": True,
                "name": platform["external_network"],
            },
        },
    }
    body = yaml.safe_dump(document, sort_keys=False)
    return "# Generated by scripts/startup.sh. The fleet YAML selects these agents.\n" + body


def _host_port(port: int) -> int:
    platform = load_platform()
    reserved = published_host_ports(platform)
    if port not in reserved:
        return port
    offset = int(platform["agent_compose"]["host_port_collision_offset"])
    shifted = port + offset
    if shifted in reserved:
        raise FleetSelectionError(f"No free host port for agent port {port}")
    return shifted


def _as_list(value: object, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) or not item.strip() for item in value):
        raise FleetSelectionError(f"{field} must be a list of directory paths")
    return [item.strip() for item in value]


def _agent_for_path(raw: str, by_path: dict[str, RegisteredAgent]) -> RegisteredAgent:
    text = raw.strip().strip("/")
    if text.endswith("config.yaml"):
        text = text[: -len("config.yaml")].strip("/")
    if text.startswith("agents/"):
        text = text[len("agents/"):]
    agent = by_path.get(text)
    if agent is None:
        raise FleetSelectionError(
            f"Unknown agent path {raw}. Use a directory under agents/."
        )
    return agent
